name: '522group14'
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.2
  - scikit-learn=1.3.2
  - numpy=1.26.0
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - pytest=7.4.3
  - click=8.1.7
  - jupyter-book=0.15.1 